version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.15

    steps:
      - checkout

      - setup_remote_docker

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-{{ checksum "go.sum" }}

      - run:
          name: Run unit tests
          command: |
            make unit

      - run:
          name: Run integration tests
          command: |
            make integration

      - run:
          name: Run e2e tests
          command: |
            make e2e

      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
