version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.15

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run:
          name: Create directory to store tests results
          command: |
            mkdir -p $TEST_RESULTS

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-{{ checksum "go.sum" }}

      - run:
          name: Run unit tests
          command: |
            gotestsum --format standard-quiet --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- -cover -race ./...

      - run:
          name: Build the project
          command: |
            go build ./cmd/sputnik-popularity

      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
