# This workflow will build a docker image and push it to Google Container
# Registry.

name: Build and push docker image to Google Container Registry

on:
  push:
    branches:
      - master
      - push-docker-image-when-merging-to-master

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT_ID }}
  IMAGE: sputnik

jobs:
  setup-build-push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - name: "Setup gcloud CLI"
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          .

    # Push the Docker image to Google Container Registry
    - name: Push
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
